import React from 'react'
import Head from 'next/head'

export default function PageHead() {
  return (
    <Head>
        <title>Learn Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
